### ISSUE TITLE
Not able to open camera screen

### ISSUE THREAD

**Issue by vishwa-3g** [Rajatkalsotra/Face-Recognition-with-Flutter#15]
I tried compiling ad running the code from the git repo and the app does run but the screen remains white and the loading wheel keeps spinning without opening of a camera and any function regarding facial recognition is done
![Screenshot_1620639987](https://user-images.githubusercontent.com/28762532/117640500-b84ffc00-b1a2-11eb-8e2c-9899aff74a22.png)

**Comment by Rajatkalsotra** [comment]
@vishwa-3g Add debug log.

**Comment by vishwa-3g** [comment]
Hey, 
Thanks for your reply!
I tried running the app on a physical device and that worked.
Once Again Thanks!
