### ISSUE TITLE
What should be threshold for RMS value between 2 embeddings ?

### ISSUE THREAD

**Issue by radha1990kumari** [Rajatkalsotra/Face-Recognition-with-Flutter#16]
I ran the model and I got the Euclidean distance between 2 different faces as 0.61 , in addition most of my values hover around 0.8-0.9 for different faces some occasionally around 1.008  , so I want to know what threshold should I choose for high accuracy

**Comment by matejsvajger** [comment]
I have the same issue. Most of the distance calculations for the faces are around this values.

On top of that, another face ranks closer to 0 than the same one from another image.

@radha1990kumari did you find any solution for this?
