### ISSUE TITLE
The plugin `firebase_ml_vision` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by omor4flutter** [Rajatkalsotra/Face-Recognition-with-Flutter#21]
i can not run anyway. just show The plugin `firebase_ml_vision` uses a deprecated version of the Android embedding. how i can run and solve it. please help anybody. thanks

**Comment by omor4flutter** [comment]
WARNING: This version of firebase_ml_vision will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.

**Comment by rjvysakh** [comment]
Project migrated to Google MLKit, you can fork the PR 
https://github.com/Rajatkalsotra/Face-Recognition-Flutter/pull/24 from here
