### ISSUE TITLE
Need help to Solve this Error.

### ISSUE THREAD

**Issue by saadsafda** [Rajatkalsotra/Face-Recognition-with-Flutter#23]
I:\websites\flutter\Face-Recognition-Flutter>flutter run
Using hardware rendering with device AOSP on IA Emulator. If you notice graphics artifacts, consider enabling software
rendering with "--enable-software-rendering".
Launching lib\main.dart on AOSP on IA Emulator in debug mode...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.12.0+3\android\build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':firebase_ml_vision'.
> Could not find the firebase_core FlutterFire plugin, have you added it as a dependency in your pubspec?

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':firebase_ml_vision'.
> compileSdkVersion is not specified.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...                              3.8s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by rjvysakh** [comment]
:firebase_ml_vision' has been discontnued and the the apis dont work. The total package with features migrated to google mlkit
https://pub.dev/packages/firebase_ml_vision check this out

**Comment by rjvysakh** [comment]
I have resolved the error. Migrated to the Google ML Kit. Find my repo here: https://github.com/rjvysakh/Face-Recognition-Flutter

**Comment by Rajatkalsotra** [comment]
Thanks @rjvysakh for the information
