### ISSUE TITLE
is there an android java implementation available?

### ISSUE THREAD

**Issue by GeorvityLabs** [Rajatkalsotra/Face-Recognition-with-Flutter#25]
flutter setup is kind of a hassle.
Step 3 is not clear , hope you can expand on Step 3.

Can you make a short youtube video on Step 1 to 4 ? 

Is there a java android version of this project available?

Thanks for such a good project! Appreciate your work making the flutter version.

**Comment by Rajatkalsotra** [comment]
Thanks @GeorvityLabs . No idea about that
